- name: set-prompt
  ansible.builtin.shell: set-prompt frontend-dev

- name: Disable Default Nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24 Version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy nginx conf file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove file application directory
  ansible.builtin.file:
    path: /user/share/nginx/html
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /user/share/nginx/html
    state: directory

- name: Unarchive a file that needs to be downloaded from URL
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /user/share/nginx/html
    remote_src: yes

- name: start nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started


